/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import MetodosDeOrdenamiento.*;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author isidro
 */
public class VentanaOrdenamiento extends javax.swing.JFrame {

    private long[] arreglo;
    private Ordenamiento ordenar;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaOrdenamiento() {
        arreglo = new long[50000];
        ordenar = new Ordenamiento();
        for (int i = 0; i < arreglo.length; i++) {
            arreglo[i] = (long) (50000 * Math.random());
        }
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Ventana principal");
        showMessageDialog(this,"Arreglo creado");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBurbuja = new javax.swing.JLabel();
        btnOrdenarBurbuja = new javax.swing.JButton();
        lblTiempoBurbuja = new javax.swing.JLabel();
        txtBurbuja = new javax.swing.JTextField();
        lblQuicksort = new javax.swing.JLabel();
        btnOrdenarQuicksort = new javax.swing.JButton();
        lblTiempoQuicksort = new javax.swing.JLabel();
        txtQuicksort = new javax.swing.JTextField();
        lblShellsort = new javax.swing.JLabel();
        btnOrdenarShellsort = new javax.swing.JButton();
        lblTiempoShellsort = new javax.swing.JLabel();
        txtShellsort = new javax.swing.JTextField();
        lblRadix = new javax.swing.JLabel();
        btnOrdenarRadix = new javax.swing.JButton();
        lblTiempoRadix = new javax.swing.JLabel();
        txtRadix = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        PaneMostrar = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBurbuja.setText("Ordenamiento Burbuja");

        btnOrdenarBurbuja.setText("Ordenar burbuja");
        btnOrdenarBurbuja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarBurbujaActionPerformed(evt);
            }
        });

        lblTiempoBurbuja.setText("Tiempo de ordenamiento:");

        txtBurbuja.setEditable(false);

        lblQuicksort.setText("Ordenamiento Quicksort");

        btnOrdenarQuicksort.setText("Ordenar quicksort");
        btnOrdenarQuicksort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarQuicksortActionPerformed(evt);
            }
        });

        lblTiempoQuicksort.setText("Tiempo de ordenamiento:");

        txtQuicksort.setEditable(false);

        lblShellsort.setText("Odernamiento Shellsort");

        btnOrdenarShellsort.setText("Ordenar shellsort");
        btnOrdenarShellsort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarShellsortActionPerformed(evt);
            }
        });

        lblTiempoShellsort.setText("Tiempo de ordenamiento:");

        txtShellsort.setEditable(false);

        lblRadix.setText("Ordenamiento Radix");

        btnOrdenarRadix.setText("Ordenar radix");
        btnOrdenarRadix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarRadixActionPerformed(evt);
            }
        });

        lblTiempoRadix.setText("Tiempo de ordenamiento:");

        txtRadix.setEditable(false);

        PaneMostrar.setEditable(false);
        PaneMostrar.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(PaneMostrar);

        jLabel1.setText("Arreglo ordenado");

        btnLimpiar.setText("Limpiar Pane");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnVolver)
                .addGap(617, 617, 617)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblBurbuja)
                                .addGap(453, 453, 453))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnOrdenarBurbuja, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblQuicksort, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnOrdenarQuicksort, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblShellsort)
                                    .addComponent(btnOrdenarShellsort, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblRadix, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnOrdenarRadix, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTiempoBurbuja)
                                    .addComponent(lblTiempoQuicksort)
                                    .addComponent(lblTiempoShellsort)
                                    .addComponent(lblTiempoRadix))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBurbuja, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtQuicksort, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtShellsort, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRadix, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnLimpiar)
                        .addGap(31, 31, 31)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(btnVolver))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(lblBurbuja)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnOrdenarBurbuja)
                                .addGap(12, 12, 12)
                                .addComponent(lblQuicksort)
                                .addGap(18, 18, 18)
                                .addComponent(btnOrdenarQuicksort)
                                .addGap(27, 27, 27)
                                .addComponent(lblShellsort)
                                .addGap(18, 18, 18)
                                .addComponent(btnOrdenarShellsort)
                                .addGap(12, 12, 12)
                                .addComponent(lblRadix)
                                .addGap(18, 18, 18)
                                .addComponent(btnOrdenarRadix))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(lblTiempoBurbuja)
                                .addGap(61, 61, 61)
                                .addComponent(lblTiempoQuicksort)
                                .addGap(76, 76, 76)
                                .addComponent(lblTiempoShellsort)
                                .addGap(61, 61, 61)
                                .addComponent(lblTiempoRadix))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBurbuja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(txtQuicksort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(txtShellsort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(txtRadix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpiar)))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrdenarBurbujaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarBurbujaActionPerformed
        long[] arregloBurbuja = arreglo;

        long inicio = System.nanoTime();
        long[] nuevoBurbuja = ordenar.Burbuja(arregloBurbuja);
        long fin = System.nanoTime();

        long tiempoTotal = fin - inicio;
        txtBurbuja.setText((tiempoTotal / 1e+9) + " segundos");
        mostrarArreglo(nuevoBurbuja);
    }//GEN-LAST:event_btnOrdenarBurbujaActionPerformed

    private void btnOrdenarQuicksortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarQuicksortActionPerformed
        long[] arregloQuick = arreglo;

        long inicio = System.nanoTime();
        ordenar.Quicksort(arregloQuick);
        long fin = System.nanoTime();

        long tiempoTotal = fin - inicio;
        txtQuicksort.setText((tiempoTotal / 1e+9) + " segundos");
        mostrarArreglo(arregloQuick);
    }//GEN-LAST:event_btnOrdenarQuicksortActionPerformed

    private void btnOrdenarShellsortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarShellsortActionPerformed
        long[] arregloShell = arreglo;

        long inicio = System.nanoTime();
        long[] nuevoShell = ordenar.Shellsort(arregloShell);
        long fin = System.nanoTime();

        long tiempoTotal = fin - inicio;
        txtShellsort.setText((tiempoTotal / 1e+9) + " segundos");
        mostrarArreglo(nuevoShell);
    }//GEN-LAST:event_btnOrdenarShellsortActionPerformed

    private void btnOrdenarRadixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarRadixActionPerformed
        long[] arregloRadix = arreglo;

        long inicio = System.nanoTime();
        long[] nuevoRadix = ordenar.Radix(arregloRadix);
        long fin = System.nanoTime();

        long tiempoTotal = fin - inicio;
        txtRadix.setText((tiempoTotal / 1e+9) + " segundos");
        mostrarArreglo(nuevoRadix);
    }//GEN-LAST:event_btnOrdenarRadixActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        PaneMostrar.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        Principal p = new Principal();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    public void mostrarArreglo(long[] arregloMostrar) {
        String mostrar = "";
        for (int i = 0; i < arregloMostrar.length; i++) {
            mostrar += "[" + (i + 1) + "] " + arregloMostrar[i] + "\n";
        }
        PaneMostrar.setText(mostrar);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaOrdenamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaOrdenamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaOrdenamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaOrdenamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaOrdenamiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane PaneMostrar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnOrdenarBurbuja;
    private javax.swing.JButton btnOrdenarQuicksort;
    private javax.swing.JButton btnOrdenarRadix;
    private javax.swing.JButton btnOrdenarShellsort;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBurbuja;
    private javax.swing.JLabel lblQuicksort;
    private javax.swing.JLabel lblRadix;
    private javax.swing.JLabel lblShellsort;
    private javax.swing.JLabel lblTiempoBurbuja;
    private javax.swing.JLabel lblTiempoQuicksort;
    private javax.swing.JLabel lblTiempoRadix;
    private javax.swing.JLabel lblTiempoShellsort;
    private javax.swing.JTextField txtBurbuja;
    private javax.swing.JTextField txtQuicksort;
    private javax.swing.JTextField txtRadix;
    private javax.swing.JTextField txtShellsort;
    // End of variables declaration//GEN-END:variables
}
